### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by DuaelFr** [Happyculture/kumquat_kickstarter#1]
@Artusamak pleaaaaaaaaaaaaaaaaaaaaaase ! ^^

**Comment by Artusamak** [comment]
Here you go.

![logo_kumquat](https://user-images.githubusercontent.com/201299/88527060-0d989380-cffd-11ea-884f-07788d51cdfe.png)

**Comment by DuaelFr** [comment]
Thanks <3
For credits: here is the used font https://www.dafont.com/smooth-butter.font

**Comment by DuaelFr** [comment]
Thanks <3
