### ISSUE TITLE
Use .ods files instead of .xlsx

### ISSUE THREAD

**Issue by Besfr** [Happyculture/kumquat_kickstarter#13]
When exporting spreadsheets with long sheets labels, there is some automatic cut that can leads to have multiple sheets with same label and one of them is rename with a generic name.
This broke the migration and prevent field to be created.

Here is an example file and spreadsheet (check the "Fields: Rémonté actualité ...." sheets)
[site_builder.xlsx](https://github.com/Happyculture/kumquat_kickstarter/files/8898867/site_builder.xlsx)
https://docs.google.com/spreadsheets/d/1idN1Fsn418yYRg-gZ_qTi0TDfNNGNgq1tvPTxF3M2Q8/edit#gid=1627343594

I tested an ods export and it does not seems to have this "cut". Altering the migrations, I successfully import my data with migrate_spreadsheet.

The ods format seems more robust and it's an open format. Only good reasons to use it instead of xlsx ;)

**Comment by DuaelFr** [comment]
See #14
